version: '3.6'
services:
  postgres:
    image: '${POSTGRES_IMAGE}'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
  graphql-engine:
    image: '${HASURA_IMAGE}'
    ports:
      - '${HASURA_GRAPHQL_SERVER_PORT}:${HASURA_GRAPHQL_SERVER_PORT}'
    depends_on:
      - 'postgres'
    volumes:
      - ./db/metadata:/metadata
      - ./db/migrations:/migrations
    restart: always
    environment:
      HASURA_GRAPHQL_SERVER_PORT: '${HASURA_GRAPHQL_SERVER_PORT}'
      HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: '${HASURA_GRAPHQL_DEV_MODE}'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: '${HASURA_GRAPHQL_ENABLED_LOG_TYPES}'
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_CLI_ENVIRONMENT: '${HASURA_GRAPHQL_CLI_ENVIRONMENT}'
      HASURA_GRAPHQL_MIGRATIONS_DIR: '${HASURA_GRAPHQL_MIGRATIONS_DIR}'
      HASURA_GRAPHQL_METADATA_DIR: '${HASURA_GRAPHQL_METADATA_DIR}'
      WORKFLOW_GRAPHQL_ENDPOINT: '${WORKFLOW_GRAPHQL_ENDPOINT}'
volumes:
  db_data:
